### ISSUE TITLE
Cannot build in Windows due to Error : Invalid Prodos File name 'BUILD\LAUNCHER.SYSTEM'.

### ISSUE THREAD

**Issue by ivorss** [a2-4am/4sports#14]
Used Cadius from https://github.com/mach-kernel/cadius
I am attaching the full log.

[log.txt](https://github.com/a2-4am/4sports/files/9742018/log.txt)

**Comment by peterferrie** [comment]
Try "winmake clean" before "winmake dsk".  It looks to me like a file-system issue on your side, because I can't reproduce the problem.

**Comment by ivorss** [comment]
The issue is resolved. I tried with the prebuilt version from here and it worked:

https://github.com/mach-kernel/cadius/releases

The problem happens only with the Cadius EXE that I built on my machine.
