### ISSUE TITLE
EPYX Street Sports BASEBALL issue

### ISSUE THREAD

**Issue by JDW1** [a2-4am/4sports#20]
Whether I am up to bat or the opposing team, after a player successfully hits the ball, the screen switches to show first base, but the players running have broken up body parts floating here and there, making the game unplayable.

Note that I am using an Apple IIe Card installed inside a Macintosh LC computer.

I am testing version 1.0-alpha.1 of Instant Replay.

**Comment by peterferrie** [comment]
fixed in e12fef6d0e0ff31ba91502c919f027f90253dfb6
