### ISSUE TITLE
THE GAMES SUMMER EDITION issue

### ISSUE THREAD

**Issue by JDW1** [a2-4am/4sports#21]
When I press Return to start play, I get a black screen. 

I am using an Apple IIe Card installed inside a Macintosh LC computer.

**Comment by peterferrie** [comment]
It never reaches the title screen?  It takes more than 10 seconds to load.  It's very slow.

**Comment by JDW1** [comment]
I will have to retest and time that to be sure, but just to confirm, are you saying that you get a totally black screen for no less than 10 seconds during the slow loading time?

**Comment by peterferrie** [comment]
Yes, that is what I am saying.  I have put activity indicators in some other titles, but I did not succeed with this one.

**Comment by a2-4am** [comment]
Closing because game does actually work, albeit suboptimally
