### ISSUE TITLE
Won't boot via Bitsy Bye?

### ISSUE THREAD

**Issue by dlxmax** [a2-4am/4sports#33]
I'm unable to boot via Bitsy Bye.
It responds with a beep and stays on the Bitsy Bye menu.
Total Replay I launches fine.

If Total Reply II is the default boot image, it comes up fine.

Test setup:
Apple IIe enhanced 128k
AppleIISd ProFile emulator (https://github.com/freitz85/AppleIISd)
ProDOS 8 v2.4.2
Total Replay I v1.0-alpha.1 image AND 04da2db built today

**Comment by dlxmax** [comment]
Moved the AppleIISd to slot 5 and that solved the problem.

**Comment by dlxmax** [comment]
Re-opening because maybe something in Total Replay II is hardcoded to slot 5, but it's not in Total Replay I?

**Comment by peterferrie** [comment]
I need more details.  If you swap the order of TR I and II in the ProFile configuration, does TR I stop working?
That BitsyBye beeps and returns suggests to me that it's the one having trouble accessing the Launcher.

**Comment by a2-4am** [comment]
Closing for lack of information. Willing to reopen if details are forthcoming
