### ISSUE TITLE
One on One hangs with Mockingboard

### ISSUE THREAD

**Issue by xotmatrix** [a2-4am/4sports#34]
One on One hangs with Mockingboard in Build 177

One on One has a known incompatibility with the Enhanced //e ROM, but the version in 4sports hangs for any type of Apple II with a Mockingboard. 

Compare `One on One (4am and san inc crack)` which behaves like the original.
https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/sports/one_on_one/One%20on%20One%20%284am%20and%20san%20inc%20crack%29.zip

Compare `one on one 20k file PRODOS (san inc pack)` which seems to have fixed the Enhanced //e compatibility problem.
https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/collections/san_inc_prodos/one%20on%20one%2020k%20file%20PRODOS%20%28san%20inc%20pack%29.po

I'm only able to test Mockingboard under emulation (AppleWin, MAME). Apple IIgs untested.

**Comment by peterferrie** [comment]
fixed in 672a89034e7df070b2f88c3fdb22ed65f9d091b3
