### ISSUE TITLE
Fuji Speedway hangs when trying to enter slideshow

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4sports#4]
ACTION.HGR/FUJI.SPEED.WAY=A

It's a lores game and there are no HGR screenshots. Hangs when attempting to load the above file.
(Not sure how to generate the auto-generated file with the above line that needs to be removed)

**Comment by frankmilliron** [comment]
res/ATTRACT/FUJI.SPEED.WAY
needs to have the entry for "ACTION.HGR/FUJI.SPEED.WAY=A" removed. There are no HGR screenshots and it hangs looking for one.

**Comment by peterferrie** [comment]
fixed in 80044e3df41c861d18ab71393254befdd64d3f84
