### ISSUE TITLE
One on One hangs in MAME and Apple2TS, problem with Mockingboard/interrupts

### ISSUE THREAD

**Issue by ct6502** [a2-4am/4sports#47]
Start up Total Replay II on the Internet Archive (via MAME), then type "O" to get to One on One, then hit return to start the game. The EA logo will come up, and it will start to fade out, then the screen will freeze.

The same thing happens with the Apple2TS emulator. I'm pretty sure it's connected to the Mockingboard driver and interrupts. If I disable the Mockingboard (or interrupts) then the game loads correctly. Presumably MAME has the same issue.

The interesting thing is that Virtual ][ is able to survive and start the game, although the Mockingboard music doesn't play.

**Comment by peterferrie** [comment]
This was fixed in 672a89034e7df070b2f88c3fdb22ed65f9d091b3, which IA doesn't have yet.

**Comment by ct6502** [comment]
Cool, thanks!
