### ISSUE TITLE
Crash during boot-up with BMOW Yellowstone disk controller

### ISSUE THREAD

**Issue by steve-chamberlin** [a2-4am/4sports#7]
Total Replay II - Instant Replay crashes during boot-up when using a Yellowstone disk controller from BMOW. It drops into the Apple II monitor at $BF05 immediately after showing the first splash screen and the text "128K" and "build 0058". Looking in the monitor, the memory range from $BF00-$BF0F is all FF and 00 values, not 6502 instructions. I'm guessing this is related to the use of soft-switches for the memory banks. The Instant Replay code may be indirectly relying on a behavior of the built-in Apple disk controller about which memory banks are selected upon exit, instead of explicitly enabling the desired banks. 

Test setup:
Apple IIe enhanced with 128K
Yellowstone disk controller in slot 6, with DIP switches set for normal operation
Floppy Emu Model C with firmware 0.2V-33, connected to Yellowstone port J1
Instant Replay build 0058

Note the original version of Total Replay (v5.0-alpha4) does not have any problem with the BMOW Yellowstone card.

**Comment by peterferrie** [comment]
I've tried to fix in 8e883b5eed5594294fc4d938cfdbf2b337188232.  Please tell me if it worked.

**Comment by steve-chamberlin** [comment]
Thanks for the fast reply! Is there a pre-built disk image available? I'm not yet set up to build the project from source, but can do it if need be.

**Comment by peterferrie** [comment]
http://pferrie.epizy.com/misc/tmp/4sports.zip

**Comment by steve-chamberlin** [comment]
Genius! That fixed it. Thanks for the super fast turn-around.

**Comment by peterferrie** [comment]
Great, but it means that your firmware is not 100% compatible with the disk II.  Upon reaching $801, A should hold the current sector number (usually $01).

**Comment by steve-chamberlin** [comment]
Thanks, I'll double-check this. It's not emulating a Disk II controller though - it's a Smartport controller similar to the Apple Liron or the Laser UDC.
